### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by gianlucasullazzo** [schmittx/home-assistant-eero#97] opened 2024-09-05 09:31 UTC
Hi, 
I see this in logs:
`Detected that custom integration 'eero' accesses hass.helpers.device_registry. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from device_registry directly at custom_components/eero/__init__.py, line 155: for device_entry in hass.helpers.device_registry.async_entries_for_config_entry(device_registry, config_entry.entry_id):, please create a bug report at https://github.com/schmittx/home-assistant-eero/issues`

Thanks,
Gianluca

**Comment by schmittx** [comment] 2024-10-08 18:55
This should be fixed in [1.6.1](https://github.com/schmittx/home-assistant-eero/releases/tag/1.6.1), please update and confirm if the issue is resolved.

**Closed by schmittx** 2024-10-08 18:55 UTC

**Comment by gianlucasullazzo** [comment] 2024-10-08 19:21
Confirm, thanks 👍
