### ISSUE TITLE
Detected blocking call to open with

### ISSUE THREAD

**Issue by RehmanAdeel** [schmittx/home-assistant-eero#93] opened 2024-08-13 22:21 UTC
Detected blocking call to open with args ('/config/custom_components/eero/api/images/logo_icon_white_background.png', 'rb') inside the event loop by custom integration 'eero' at custom_components/eero/api/__init__.py, line 69: self.default_qr_code = open(EERO_LOGO_ICON, "rb").read() if show_eero_logo else None (offender: /config/custom_components/eero/api/__init__.py, line 69: self.default_qr_code = open(EERO_LOGO_ICON, "rb").read() if show_eero_logo else None), please create a bug report at https://github.com/schmittx/home-assistant-eero/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eero/__init__.py", line 180, in async_setup_entry
    api = EeroAPI(
  File "/config/custom_components/eero/api/__init__.py", line 69, in __init__
    self.default_qr_code = open(EERO_LOGO_ICON, "rb").read() if show_eero_logo else None

**Comment by schmittx** [comment] 2024-10-08 18:58
I was not able to reproduce this, are you still experiencing a problem?

**Comment by maxm77-RC** [comment] 2024-10-16 13:11
I see you were unable to reproduce the issue previously. Let me know if you need further information.

**Comment by schmittx** [comment] 2024-10-16 15:34
This should be fixed in [1.6.2](https://github.com/schmittx/home-assistant-eero/releases/tag/1.6.2); please update and confirm.

**Closed by schmittx** 2024-10-16 15:34 UTC
Labels: bug

**Comment by maxm77-RC** [comment] 2024-10-16 18:28
Wow that was speedy - thank you. 

Sorry to ask, but is it just a question of overwriting the files in the custom_components folder? 

Thanks

**Comment by schmittx** [comment] 2024-10-16 18:48
> Sorry to ask, but is it just a question of overwriting the files in the custom_components folder?

Yep, exactly.

**Comment by maxm77-RC** [comment] 2024-10-16 19:15
Thank you - all looking good so far :-)
