### ISSUE TITLE
"Unknown error occurred."

### ISSUE THREAD

**Issue by PartyingChair** [schmittx/home-assistant-eero#77] opened 2024-01-15 01:19 UTC
Tried authentication with email and with phone. Both just give me unknown error with no other info. Waited 2 days, tried again same error.

**Comment by rogorvi** [comment] 2024-01-21 17:47
I got the same error with my email. When I try the phone option I get the message "Enter the verification code that was sent to..." but no code is received.

**Comment by nsalazar** [comment] 2024-02-01 20:43
I also got the error AFTER i input the verification code 
![eeroerror](https://github.com/schmittx/home-assistant-eero/assets/1181656/832bf3b5-b5ef-4b5e-bfab-37b750efcd36)

I had a configuration already working until a few days ago when I just noticed the error. I tried to press the button Configure in Integrations, but I got another error.
Then I deleted it and started from zero, but this error below appeared:

Here is the log of the error when after Verify Eero account:
```
2024-02-01 17:26:55.648 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 416, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/config_flow.py", line 103, in async_step_verify
    self.response = await self.hass.async_add_executor_job(self.api.update)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/api/__init__.py", line 197, in update
    update_data["release_notes"] = self.get_release_notes(url=update_data["manifest_resource"])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/api/__init__.py", line 85, in get_release_notes
    raise EeroException(response)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/api/__init__.py", line 34, in __init__
    data = json.loads(response.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by thayerfox** [comment] 2024-02-09 04:15
> I also got the error AFTER i input the verification code ![eeroerror](https://private-user-images.githubusercontent.com/1181656/301638510-832bf3b5-b5ef-4b5e-bfab-37b750efcd36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NTIyNzYsIm5iZiI6MTcwNzQ1MTk3NiwicGF0aCI6Ii8xMTgxNjU2LzMwMTYzODUxMC04MzJiZjNiNS1iNWVmLTRiNWUtYmZhYi0zN2I3NTBlZmNkMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDlUMDQxMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGEzZDNmOWQxMjY0NTM3MTA3ZGFhOTc0NTIwYTMwNzY3MzY3ZWFkZjU4MDkxNDNmYzE5NjZhOWVkY2I4NTQ2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K0sHAQKThyJ3dtA6KnSrMoTfs5bc6XmHflM1QRzHZms)
> 
> I had a configuration already working until a few days ago when I just noticed the error. I tried to press the button Configure in Integrations, but I got another error. Then I deleted it and started from zero, but this error below appeared:
> 
> Here is the log of the error when after Verify Eero account:
> 
> ```
> 2024-02-01 17:26:55.648 ERROR (MainThread) [aiohttp.server] Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
>     resp = await request_handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
>     resp = await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
>     response = await handler(request)
>                ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
>     result = await handler(request, **request.match_info)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
>     return await func(self, request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
>     return await super().post(request, flow_id)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
>     result = await method(view, request, data, *args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
>     result = await self._flow_mgr.async_configure(flow_id, data)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in async_configure
>     result = await self._async_handle_step(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 416, in _async_handle_step
>     result: FlowResult = await getattr(flow, method)(user_input)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/eero/config_flow.py", line 103, in async_step_verify
>     self.response = await self.hass.async_add_executor_job(self.api.update)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/eero/api/__init__.py", line 197, in update
>     update_data["release_notes"] = self.get_release_notes(url=update_data["manifest_resource"])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/eero/api/__init__.py", line 85, in get_release_notes
>     raise EeroException(response)
>           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/eero/api/__init__.py", line 34, in __init__
>     data = json.loads(response.text)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```

I have the same issue.  It was working fine until the update to 2024.2.  Tried to reconfigure after the update, got error 500.  Uninstalled, reinstalled and tried multiple times to set up, both via email and phone.

Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 8:02:04 PM (1 occurrences)
Last logged: 8:02:04 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/config_flow.py", line 103, in async_step_verify
    self.response = await self.hass.async_add_executor_job(self.api.update)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/api/__init__.py", line 197, in update
    update_data["release_notes"] = self.get_release_notes(url=update_data["manifest_resource"])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/api/__init__.py", line 85, in get_release_notes
    raise EeroException(response)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/api/__init__.py", line 34, in __init__
    data = json.loads(response.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by rogorvi** [comment] 2024-02-09 06:19
For me this was solved by using an email account instead of my amzon account to login into my eero. See the notes from the readme:
"This integration does not support login via Amazon account. A workaround is to create a new account without Amazon login and add that account as another network admin."

**Comment by PartyingChair** [comment] 2024-02-09 06:23
I am not using an Amazon account, and never was.

**Comment by thayerfox** [comment] 2024-02-09 06:32
It seems to be an issue parsing the release notes section of the API JSON.  

Commenting out this line:
update_data["release_notes"] = self.get_release_notes(url=update_data["manifest_resource"])
and rebooting will allow the integration to authenticate.  The lastest FW sensors of the Eero devices won't work though.

**Comment by PacoCT** [comment] 2024-02-22 21:52
Hi,

I'm having the same error.

I do not understand "A workaround is to create a new account without Amazon login and add that account as another network admin". Where is this account supposed to be create?

Line 197 of my version in _init_.py is 
        raise UpdateFailed(f"Error communicating with API: {exception.error_message}")

Is that the line that needs to be commented?

Thanks in advance

**Comment by thayerfox** [comment] 2024-02-22 22:02
The line that needs to be commented out is 
`update_data["release_notes"] = self.get_release_notes(url=update_data["manifest_resource"])`

which is 197 of eero\**api**\--init--py

**Comment by PacoCT** [comment] 2024-02-23 07:41
> The line that needs to be commented out is `update_data["release_notes"] = self.get_release_notes(url=update_data["manifest_resource"])`
> 
> which is 197 of eero\api\ --init--py not eero\ --init--.py

Thank you very much!!
I was looking at the wrong --init--.py
That did it, now I went one step further :-)

Now, the integration is installed but my eero network doesn't appear. It could be because I've HA installed in a PC connected by ethernet to my network. I'll keep trying.
Regards,

**Comment by PacoCT** [comment] 2024-02-23 07:56
> Hi,
> 
> I'm having the same error.
> 
> I do not understand "A workaround is to create a new account without Amazon login and add that account as another network admin". Where is this account suppose to be created?
> 
> Line 197 of my version in _init_.py is raise UpdateFailed(f"Error communicating with API: {exception.error_message}")
> 
> Is that the line that needs to be commented?
> 
> Thanks in advance

I figured out the "create a new account" issue: the account need to be created in the eero app.

Creating a New eero Account:
While the eero system allows linking with an Amazon account, creating a separate eero account offers more control and flexibility. Here's a step-by-step guide on how to do it within the eero app:

Invite a New Admin:

Start by inviting the "new" account to become an admin on your existing eero network. This can be done through the app's sharing settings.
Important: Ensure this new admin has a unique email address that hasn't been used for an eero account before.

Log Out of the Amazon Connected Account :
If you previously connected your eero to an Amazon account, you can log out of it if desired. 
To log out, go to the app's settings and find the connected accounts section.

Create a New eero Account:
On the invited admin's device, open the eero app and select "Create Account."
Enter the new admin's unique email address and create a strong password.
Verify the account using the email sent to the new address.

Log In with the New Account:
Back on the invited admin's device, log in to the eero app using the newly created account credentials.

Accept the Invitation:
The invited admin should receive a notification within the app to accept the invitation to join the network.
Tap "Accept" to join the network with the new account.

**Comment by schmittx** [comment] 2024-03-01 13:59
@PacoCT Thanks for the detailed instructions for creating a new eero account, I'll add it to the documentation.

@thayerfox You're correct, the eero firmware release history and notes are incorrect on eero's side. Only thing that can be done is to update the integration to fail more gracefully. I'll try to push an update soon. Otherwise, commenting that line out is the best bet.

**Comment by thayerfox** [comment] 2024-03-01 23:08
@schmittx, I actually have a support ticket in with eero, as the software version history is also broken in their latest android app.  No resolution for the official app so far, but it did get escalated to a support engineer.

**Comment by schmittx** [comment] 2024-03-05 04:10
I published a beta [release](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0b0) with multiple bug fixes, give a try and let me know if it helps.

**Comment by thayerfox** [comment] 2024-03-05 04:22
The integration loaded without errors, but all the entities are unavailable.  Selecting configure in the integration does not show any networks in the popup.  Do I need to remove and re add the network again?  No errors in the log either.

**Comment by schmittx** [comment] 2024-03-05 11:26
Strange. Before deleting the integration can you try enabling debug logging and/ saving responses from the configure menu?

**Comment by thayerfox** [comment] 2024-03-05 19:20
<img width="303" alt="image" src="https://github.com/schmittx/home-assistant-eero/assets/3465633/977a7ac6-a534-404f-b447-8636f5ec88ae">

<img width="436" alt="image" src="https://github.com/schmittx/home-assistant-eero/assets/3465633/4251ba38-e62d-4120-a9f6-c8ef2ba9020e">

2024-03-04 20:16:11.724 DEBUG (SyncWorker_3) [custom_components.eero.api]
- EeroException
- Code: 404
- Error: Unable to get release notes
2024-03-04 20:16:17.552 DEBUG (MainThread) [custom_components.eero] Finished fetching Eero (ThayerFox) data in 7.840 seconds (success: True)

I tried to remove and readd, same thing.

**Comment by schmittx** [comment] 2024-03-06 16:26
@thayerfox I published an [update](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0b1) to the beta. Please install and let me know if it resolves the issue.

**Comment by thayerfox** [comment] 2024-03-06 17:39
@schmittx the b1 version solved the initialization issue.  Only thing now seems to be this extra radiobox in the configure screen.  Perhaps because I don't have eero premium?

<img width="427" alt="image" src="https://github.com/schmittx/home-assistant-eero/assets/3465633/450718e7-dac9-4312-987b-5081ac428ed8">

**Comment by schmittx** [comment] 2024-03-06 18:06
@thayerfox Glad to hear it. Regarding the config screen, it looks like a frontend issue because you're missing text regarding QR code option (the 2nd radio box). Make sure you're copying `strings.json` and the translations folder (including `en.json` inside) over as well. Then do a hard refresh and/or clear the cache of your browser to ensure the frontend updates.

**Comment by thayerfox** [comment] 2024-03-06 19:06
Those were copied, and I did do a ctrl+f5 on the page.  Same issue on mobile too.

There doesn't seem to be anything in that container?

**Comment by schmittx** [comment] 2024-03-06 19:30
@thayerfox I'm not very experienced with frontend work so I'm running out of suggestions unfortunately. Things seem fine on my end, and inspection shows content in that container. I'd imagine there'd be more complaints if this was a widespread issue. Only other thing I can think is that you've set the language for your Home Assistant profile to something other than American English?

![image](https://github.com/schmittx/home-assistant-eero/assets/630673/c2b3380f-76d3-4796-83fc-b99b3ea44d64)

**Comment by thayerfox** [comment] 2024-03-06 19:58
I had it set to Canada/English, but no change when changing local to US/English.

Its not a huge issue, especially since I can see what the option is supposed to be with your screenshot.

**Comment by schmittx** [comment] 2024-03-06 20:16
Understood, glad you can at least use it though. Any chance it's a browser-specific issue? Have you tried with Chrome, Safari, Edge, etc.?

**Comment by thayerfox** [comment] 2024-03-06 20:18
I've tried with chrome and edge on windows and chrome on android.  Same thing, very odd.

**Comment by schmittx** [comment] 2024-03-06 22:18
Closing this as the beta updates have been reflected into newest release [here](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0).

**Closed by schmittx** 2024-03-06 22:18 UTC
Labels: bug

**Comment by thayerfox** [comment] 2024-03-07 00:06
@schmittx I just updated to 2024.3 and magically the QR code option started displaying correctly.  Something must have been cached I guess.  
<img width="425" alt="image" src="https://github.com/schmittx/home-assistant-eero/assets/3465633/4c435606-07dc-4b55-b2b5-97e2050f919c">

Thanks for your help!

**Comment by schmittx** [comment] 2024-03-07 00:26
@thayerfox Awesome, glad it's resolved now!

**Comment by tncrosby** [comment] 2025-01-10 17:12
I"ve been trying to get this Eero custom integration to work but I keep getting this error. 
Any clue where I can start?


This error originated from a custom integration.

Logger: custom_components.eero
Source: helpers/update_coordinator.py:379
integration: eero (documentation, issues)
First occurred: 9:43:29 AM (6 occurrences)
Last logged: 12:05:18 PM

Unexpected error fetching Eero (***my user name***) data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/__init__.py", line 195, in async_update_data
    return await hass.async_add_executor_job(api.update, conf_networks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eero/api/__init__.py", line 260, in update
    activity_data[resource][activity] = self.update_activity(
                                        ~~~~~~~~~~~~~~~~~~~~^
        activity=activity,
        ^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        timezone=network_data["timezone"]["value"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/eero/api/__init__.py", line 285, in update_activity
    start, end, cadence = self.define_period(
                          ~~~~~~~~~~~~~~~~~~^
        period=ACTIVITY_MAP[activity][2],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        timezone=timezone,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/eero/api/__init__.py", line 101, in define_period
    now = datetime.datetime.now(tz=pytz.timezone(timezone))
                                   ~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pytz/__init__.py", line 168, in timezone
    raise UnknownTimeZoneError(None)
pytz.exceptions.UnknownTimeZoneError: None

**Comment by schmittx** [comment] 2025-01-10 17:53
@tncrosby It seems like there might be an issue with the timezone for your network as I just reconfirmed that the integration works without any errors for my network. To start with, can you confirm that there's a valid timezone set for your network via the eero app ("Settings" > ""Nickname and timezone")?
